# Generated by Django 4.2.16 on 2024-11-24 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='proImages/')),
                ('description', models.TextField(blank=True)),
                ('timezone', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_type', models.CharField(choices=[('Car', 'Car'), ('Product', 'Product'), ('Docuement', 'Docuement'), ('Other', 'Other')], max_length=11)),
            ],
        ),
    ]
